version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  #  1st test set
  saucedemo-module:
    # https://hub.docker.com/repository/docker/anishst/selenium-docker
    image: anishst/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=saucedemo_tests.xml
    # store results in reports folder
    volumes:
      # store reports in /reports/saucedemo
      - ./reports/saucedemo:/usr/share/selenium_docker/test-output
  #  2nd test set
  duck-search-module:
    image: anishst/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=duck_search_tests.xml
    #    store results in reports folder
    volumes:
      # store reports in /reports/ducksearch
      - ./reports/ducksearch:/usr/share/selenium_docker/test-output